services:
  app:
    container_name: floresta-limpa-visualizer
    build:
      context: .
      args:
        - PORT=${PORT:-7010}
    ports:
      - "${PORT:-7010}:${PORT:-7010}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-7010}
    restart: unless-stopped
    develop:
      watch:
        # Auto-restart on TypeScript source changes
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - "**/*.test.ts"
            - "**/*.spec.ts"
       
        # Restart on package.json changes
        - action: sync+restart
          path: ./package.json
          target: /app/package.json
       
        # Restart on environment file changes
        - action: sync+restart
          path: ./.env
          target: /app/.env
       
        # Rebuild on Dockerfile changes
        - action: rebuild
          path: ./Dockerfile